### ISSUE TITLE
我要投稿「版主真的不會寫前端 2019 排行榜」的「標題」

### ISSUE THREAD

**Issue by DongGuaLemon** [init-engineer/init.engineer-frontend-template#5]
發在PR #4有程式碼和圖片，麻煩版主了。

**Comment by Kantai235** [comment]
哈囉，這幾天稍微抽空看了一下，好像有點問題，如果 `doodles` 的 `z-index` 被設定為 `-1` 的話，那麼 `css-doodle` 將會被星星背景給覆蓋過去，這部分可能需要修正一下。

另外推薦加入 `Discord` 頻道，一起討論活動哦！
[https://discord.gg/tPhnrs2](https://discord.gg/tPhnrs2)
